### ISSUE TITLE
Library Updates Not Syncing 

### ISSUE THREAD

**Issue by PrinceAndy63** [Drumber/Kitsune#19] opened 2023-10-01 03:15 UTC
Any library updates made in the app are not syncing back to Kitsu.

09-30 23:08:33.973  3711  3778 D LibraryManager: Synchronizing 1 offline modifications...
09-30 23:08:34.222  3711  3778 E LibraryManager: Failed to synchronize library entry 96423765
09-30 23:08:34.222  3711  3778 E LibraryManager: retrofit2.HttpException: HTTP 400

**Comment by PrinceAndy63** [comment] 2023-10-01 03:16
[Kitsune_2023-09-30_23-08-54.txt](https://github.com/Drumber/Kitsune/files/12776037/Kitsune_2023-09-30_23-08-54.txt)

**Comment by Drumber** [comment] 2023-10-01 09:13
Thanks for providing the logs. It is really strange that the server returns a 400 HTTP code. That would basically mean that the library update request was somehow malformed. Haven't seen that before yet.
It would be helpful if you could give me some more context, such as steps to reproduce.

But since I have completely refactored the library management in the latest update, it's quite possible that the bug no longer exists in v1.8.0. Therefore, please update to the latest version and if you encounter any errors again, feel free to respond to this issue or open a new one.

**Comment by PrinceAndy63** [comment] 2023-10-01 12:27
Thanks for taking a look. I have updated to v1.8.0 but the unfortunately has issues updating the library. The new error now shows in the GUI as "Failed to update library entry". The same error happens on WiFi or mobile data. I've checked DNS logs while on WiFi and there are no blocked entries that would like up with the testing (I run AdGuard Home for DNS ad blocking). Android Private DNS was disabled for mobile data testing, so no DNS filtering.

My device I'm using is a Google Pixel Fold, running the Android 14 QPR Beta 1 build U1B1.230908.003 (probably a huge factor).

I've made a screen recording on reproducing the error from a clean install (stored on OneDrive): https://1drv.ms/v/s!Akc_qyFJBJTajJAbAnoAzGKbAD-FsA

Here are the logs from the testing:
[Kitsune_2023-10-01_07-40-48.txt](https://github.com/Drumber/Kitsune/files/12777106/Kitsune_2023-10-01_07-40-48.txt)

Please let me know if you need any additional information.

**Comment by Drumber** [comment] 2023-10-01 13:12
Thanks for the detailed information. Unfortunately I cannot reproduce the error on my device.
Could you please try the same thing with the debug build below and send the logs again. The debug build will also log the network requests and should give a bit more insight into what is going on.

Here's the debug build: https://workupload.com/file/MMqVJ2Svf78

**Comment by PrinceAndy63** [comment] 2023-10-01 13:20
I've just installed the debug build and reproduced the error. Please find the logs below. 

Thanks for letting me know it will show up twice in the app drawer.

[Kitsune_2023-10-01_09-14-32.txt](https://github.com/Drumber/Kitsune/files/12777251/Kitsune_2023-10-01_09-14-32.txt)

**Comment by Drumber** [comment] 2023-10-01 13:24
Sorry, I have deleted your comment as a precaution, because possibly sinsible user data could be logged in the debug logs.

**Comment by Drumber** [comment] 2023-10-01 13:43
The previous debug build logged all HTTP requests including the authentication request, which contained sensitive credentials. That's now fixed and there shouldn't be any sensitive user data in the logs now.

Here's the fixed build: https://workupload.com/file/v7k7vu6pHC4

**Comment by PrinceAndy63** [comment] 2023-10-01 13:53
Thanks for looking out. I've installed the newest debug build and reproduced the error. Please find the logs below.

[Kitsune_2023-10-01_09-52-08.txt](https://github.com/Drumber/Kitsune/files/12777307/Kitsune_2023-10-01_09-52-08.txt)

**Comment by Drumber** [comment] 2023-10-01 14:05
Thanks a lot! I have found the source of the problem. Somehow a parameter "stability" is sent in the library update request, which should not be there.

Request body:
`{"data":{"type":"libraryEntries","id":"123456","attributes":{"progress":4,"stability":0}}}`
Response body:
`"errors":[{"title":"Param not allowed","detail":"stability is not allowed.","code":"105","status":"400"}]}`

I will look into that and try to track down where the paramter is coming from.

**Comment by PrinceAndy63** [comment] 2023-10-01 14:11
Thanks for the update! Great you were able to find the source of the issue.

**Comment by Drumber** [comment] 2023-10-01 18:49
Wow, it took longer than I thought to track down this odd "stability" property.  But the bug should be fixed now.
Could you test the build below to verify. If everything is working now, I will release a hot-fix tomorrow.

Fixed build: https://workupload.com/file/kmhsF9nT3y8

**Comment by PrinceAndy63** [comment] 2023-10-01 19:04
Awesome work! All looks good now; I updated an anime library entry successfully. 

Logs attached for reference if you'd like to review:
[Kitsune_2023-10-01_15-02-13.txt](https://github.com/Drumber/Kitsune/files/12777985/Kitsune_2023-10-01_15-02-13.txt)

**Comment by Drumber** [comment] 2023-10-02 09:34
Fix got released in v1.8.1.

Thanks for your help!

**Closed by Drumber** 2023-10-02 09:34 UTC
Labels: bug
